CREATE EXTERNAL TABLE rats (time INT, voltage SMALLINT)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/neuro/input';

SELECT time, AVG(voltage)
FROM rats
GROUP BY time ORDER BY time;